-- MySQL Script generated by MySQL Workbench

-- Fri Jun 17 21:23:48 2022

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @ @SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------

-- Schema findinn

-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `findinn` ;

-- -----------------------------------------------------

-- Schema findinn

-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `findinn` DEFAULT CHARACTER SET utf8 ;

USE `findinn` ;

-- -----------------------------------------------------

-- Table `findinn`.`pais`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`pais` ;

CREATE TABLE IF NOT EXISTS `findinn`.`pais` (
    `id_pais` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id_pais`)
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`usuario`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`usuario` ;

CREATE TABLE IF NOT EXISTS `findinn`.`usuario` (
    `id_usuario` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(90) NOT NULL,
    `cpf` VARCHAR(11) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `senha` VARCHAR(45) NOT NULL,
    `telefone` VARCHAR(9) NOT NULL,
    `locatario` TINYINT NULL,
    `anfitriao` TINYINT NULL,
    `id_pais` INT NOT NULL,
    PRIMARY KEY (`id_usuario`),
    CONSTRAINT `fk_usuario_pais1` FOREIGN KEY (`id_pais`) REFERENCES `findinn`.`pais` (`id_pais`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`estado`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`estado` ;

CREATE TABLE IF NOT EXISTS `findinn`.`estado` (
    `id_estado` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(45) NOT NULL,
    `id_pais` INT NOT NULL,
    PRIMARY KEY (`id_estado`),
    CONSTRAINT `fk_estado_pais1` FOREIGN KEY (`id_pais`) REFERENCES `findinn`.`pais` (`id_pais`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`cidade`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`cidade` ;

CREATE TABLE IF NOT EXISTS `findinn`.`cidade` (
    `id_cidade` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(45) NOT NULL,
    `estado_id_estado` INT NOT NULL,
    PRIMARY KEY (`id_cidade`),
    CONSTRAINT `fk_cidade_estado1` FOREIGN KEY (`estado_id_estado`) REFERENCES `findinn`.`estado` (`id_estado`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`tipo_acomodacao`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`tipo_acomodacao` ;

CREATE TABLE IF NOT EXISTS `findinn`.`tipo_acomodacao` (
    `id_tipo_acomodacao` INT NOT NULL AUTO_INCREMENT,
    `descricao` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id_tipo_acomodacao`)
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`acomodacao`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`acomodacao` ;

CREATE TABLE IF NOT EXISTS `findinn`.`acomodacao` (
    `id_acomodacao` INT NOT NULL AUTO_INCREMENT,
    `id_usuario` INT NOT NULL,
    `id_cidade` INT NOT NULL,
    `cep` VARCHAR(8) NOT NULL,
    `rua` VARCHAR(45) NOT NULL,
    `numero` VARCHAR(3) NOT NULL,
    `complemento` VARCHAR(90) NULL,
    `valor_diaria` DECIMAL NOT NULL,
    `imagem_principal` VARCHAR(45) NOT NULL,
    `imagem_secundaria` VARCHAR(45) NULL,
    `descricao` VARCHAR(255) NULL,
    `capacidade` VARCHAR(45) NOT NULL,
    `id_tipo_acomodacao` INT NOT NULL,
    PRIMARY KEY (`id_acomodacao`),
    CONSTRAINT `fk_acomodacao_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `findinn`.`usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_acomodacao_cidade1` FOREIGN KEY (`id_cidade`) REFERENCES `findinn`.`cidade` (`id_cidade`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_acomodacao_tipo_acomodacao1` FOREIGN KEY (`id_tipo_acomodacao`) REFERENCES `findinn`.`tipo_acomodacao` (`id_tipo_acomodacao`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`adicional_acomodacao`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`adicional_acomodacao` ;

CREATE TABLE IF NOT EXISTS `findinn`.`adicional_acomodacao` (
    `id_adicional_acomodacao` INT NOT NULL AUTO_INCREMENT,
    `tipo_adicional` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id_adicional_acomodacao`)
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`cartao`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`cartao` ;

CREATE TABLE IF NOT EXISTS `findinn`.`cartao` (
    `id_cartao` INT NOT NULL AUTO_INCREMENT,
    `titular` VARCHAR(45) NOT NULL,
    `numero` VARCHAR(45) NOT NULL,
    `vencimento` DATE NOT NULL,
    `cvv` VARCHAR(3) NOT NULL,
    `id_usuario` INT NOT NULL,
    PRIMARY KEY (`id_cartao`),
    CONSTRAINT `fk_cartao_usuario1` FOREIGN KEY (`id_usuario`) REFERENCES `findinn`.`usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`locacao`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`locacao` ;

CREATE TABLE IF NOT EXISTS `findinn`.`locacao` (
    `id_locacao` INT NOT NULL,
    `data_inicio` DATETIME NOT NULL,
    `data_fim` DATETIME NOT NULL,
    `check_in` TINYINT NULL,
    `multa` DECIMAL NULL,
    `id_acomodacao` INT NOT NULL,
    `id_usuario` INT NOT NULL,
    `cartao_id_cartao` INT NOT NULL,
    PRIMARY KEY (`id_locacao`),
    CONSTRAINT `fk_locacao_acomodacao1` FOREIGN KEY (`id_acomodacao`) REFERENCES `findinn`.`acomodacao` (`id_acomodacao`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_locacao_usuario1` FOREIGN KEY (`id_usuario`) REFERENCES `findinn`.`usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_locacao_cartao1` FOREIGN KEY (`cartao_id_cartao`) REFERENCES `findinn`.`cartao` (`id_cartao`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`anuncio`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`anuncio` ;

CREATE TABLE IF NOT EXISTS `findinn`.`anuncio` (
    `id_anuncio` INT NOT NULL AUTO_INCREMENT,
    `data_inicio` DATETIME NOT NULL,
    `data_fim` DATETIME NOT NULL,
    `valor` DECIMAL NOT NULL,
    `anunciocol` VARCHAR(45) NULL,
    `id_acomodacao` INT NOT NULL,
    PRIMARY KEY (`id_anuncio`),
    CONSTRAINT `fk_anuncio_acomodacao1` FOREIGN KEY (`id_acomodacao`) REFERENCES `findinn`.`acomodacao` (`id_acomodacao`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `findinn`.`adicional_acomodacao_has_acomodacao`

-- -----------------------------------------------------

DROP TABLE IF EXISTS `findinn`.`adicional_acomodacao_has_acomodacao`;

CREATE TABLE IF NOT EXISTS `findinn`.`adicional_acomodacao_has_acomodacao` (
    `id_adicional_acomodacao` INT NOT NULL,
    `id_acomodacao` INT NOT NULL,
    PRIMARY KEY (`id_adicional_acomodacao`, `id_acomodacao`),
    CONSTRAINT `fk_adicional_acomodacao_has_acomodacao_adicional_acomodacao1` FOREIGN KEY (`id_adicional_acomodacao`) REFERENCES `findinn`.`adicional_acomodacao` (`id_adicional_acomodacao`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_adicional_acomodacao_has_acomodacao_acomodacao1` FOREIGN KEY (`id_acomodacao`) REFERENCES `findinn`.`acomodacao` (`id_acomodacao`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;